### ISSUE TITLE
typo in Hacking the Linux Kernel in Ada – Part 3 

### ISSUE THREAD

**Issue by anhvofrcaus** [ohenley/adacore_jetson#2]
It is a great work. Thank you for sharing.

The description, as repeated below, was correct. However, the actual code was missing package Ic as of Ic.Unsigned.

Wq_Flags : Ic.Unsigned with Address => Flags'Address; -- voila!

**Comment by ohenley** [comment]
I communicated the error. It should be fixed shortly. Thank you!
